// Code generated by protoc-gen-lemontypes. DO NOT EDIT.
// source: proto/testpb/testpb.proto
// file.Proto.GetName():proto/testpb/testpb.proto
// import path: []

export class HelloRequest {
  name: string
}
