// Code generated by protoc-gen-lemontypes. DO NOT EDIT.

export enum TestEnum {
  HTTP = 0,	// SIZE=1
  HTTPS = 2,	// SIZE=1
  FTP = 5,	// SIZE=1
}

export interface TestStruct {
  protocol: TestEnum
  host: string
  port: number
  is_secure?: boolean
  password: string
  token: bigint
}
