// Code generated by protoc-gen-lemontypes. DO NOT EDIT.
// source: proto/test.proto
// file.Proto.GetName():proto/test.proto
// import path: [google/protobuf/timestamp.proto proto/testpb/testpb.proto]

export enum TestEnum {
  HTTP = 0,	// SIZE=1
  HTTPS = 2,	// SIZE=1
  FTP = 5,	// SIZE=1
}

export class TestStruct {
  protocol: TestEnum
  host: string
  port: number
  is_secure?: boolean
  created_at: Timestamp
  hello: HelloRequest
  password: string
  token: bigint
}
